spring:
  flyway:
    user: 'postgres'
    password: 'password'
    url: 'jdbc:postgresql://postgres:5432/postgres'
    baseline-on-migrate: true
  datasource:
    url: 'jdbc:postgresql://postgres:5432/postgres'
    username: 'postgres'
    password: 'password'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: validate

FAMILY_MEMBER_URL: ${FAMILY_MEMBER_URL}
CREATE_FAMILY_MEMBER_URL: 'createfamilymember'
RETURN_FAMILY_MEMBER_URL: 'getfamilymembers'