spring:
  flyway:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_DATABASE_URL}
    baseline-on-migrate: true
  datasource:
    url: ${POSTGRES_DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: validate

family:
  member:
    url: ${FAMILY_MEMBER_URL}
create:
  family:
    member:
      url: ${CREATE_FAMILY_MEMBER_URL}
return:
  family:
    member:
      url: ${RETURN_FAMILY_MEMBERS_URL}