version: '3.8'
services:

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/postgres -schemas=public -connectRetries=60 migrate -user=postgres -password=password
    volumes:
      - ./flyway:/flyway/sql/
    depends_on:
      - postgres

  family-app:
    restart: on-failure
    build:
      context: ./FamilyApp
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  family-member-app:
    restart: on-failure
    build:
      context: ./FamilyMemberApp
      dockerfile: Dockerfile
    ports:
      - 8000:8000